src/blog_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('user/', include('user_app.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

src/main_app/urls.py
from django.urls import path
from . import views

app_name = "main"
urlpatterns = [
    path('', views.display_home_page, name='home'),
    path('create_post/', views.create_post, name='create_post'),
    path('post_list/', views.display_post_list, name='post_list'),
    path('post/<str:slug>/details/', views.display_post_details, name='post_details'),
    path('post/<str:slug>/delete/', views.delete_post, name='delete_post'),
    path('post/<str:slug>/update/', views.update_post, name='update_post'),
    path('post/<str:slug>/like/', views.like_post, name='like_post'),
]

src/main_app/models.py
from django.db import models
from django.contrib.auth.models import User


def user_directory_path(instance, filename):
    return f'blog/{instance.author.id}/{filename}'

# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=100)

    class Meta:
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.name


class Post(models.Model):
    OPTIONS = (
        ('d', 'Draft'),
        ('p', 'Published')
    )

    title = models.CharField(max_length=100)
    content = models.TextField()
    image = models.ImageField(
        upload_to=user_directory_path, default='no_image.jpg')
    category = models.ForeignKey(Category, on_delete=models.PROTECT)
    publish_date = models.DateTimeField(auto_now_add=True)
    last_update = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    status = models.CharField(max_length=10, choices=OPTIONS, default='d')
    slug = models.SlugField(blank=True, unique=True)

    def __str__(self):
        return self.title
    
    def get_comment_count(self):
        return self.comment_set.count()
    
    def get_like_count(self):
        return self.like_set.count()
    
    def get_postview_count(self):
        return self.postview_set.count()
    
    def get_comments(self):
        return self.comment_set.all()


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    time_stamp = models.DateTimeField(auto_now_add=True)
    content = models.TextField()

    def __str__(self):
        return self.user.username
    
    class Meta:
        ordering = ('-time_stamp',)        


class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username


class PostView(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    time_stamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username

src/main_app/forms.py
from django import forms
from .models import Category, Post, Comment


class PostForm(forms.ModelForm):
    status = forms.ChoiceField(choices=Post.OPTIONS)
    category = forms.ModelChoiceField(
        queryset=Category.objects.all(), empty_label="Select")

    class Meta:
        model = Post
        exclude = ('slug', 'author', 'last_update', 'publish_date')


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('content', )

src/main_app/views.py
from django.http.response import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from main_app.forms import CommentForm, PostForm
from main_app.models import Post, Like, PostView
from django.contrib.auth.decorators import login_required
from django.contrib import messages

# Create your views here.


def display_home_page(request):
    return render(request, 'main_app/home_page.html')


@login_required()
def create_post(request):
    form = PostForm()
    context = {
        'form': form
    }
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            print(request.FILES)
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            messages.success(request, "Post created successfully!")
            return redirect('main:home')
    return render(request, 'main_app/create_post.html', context)


def display_post_list(request):
    post_list = Post.objects.filter(status='p')
    context = {
        'post_list': post_list
    }
    return render(request, 'main_app/post_list.html', context)


def display_post_details(request, slug):
    form = CommentForm()
    post = get_object_or_404(Post, slug=slug)

    # def commenton_thepost()
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.user = request.user
            comment.post = post
            comment.save()
            return redirect("main:post_details", slug=slug)
            # return redirect(request.path)
    context = {
        'post': post,
        'form': form
    }

    # POSTVIEW LOGIC
    if request.user.is_authenticated:
        PostView.objects.get_or_create(user=request.user, post=post)
        # get_or_create() => create if there is not

    return render(request, 'main_app/post_details.html', context)


@login_required()
def update_post(request, slug):
    post = get_object_or_404(Post, slug=slug)
    form = PostForm(request.POST or None, request.FILES or None, instance=post)
    context = {
        'form': form,
        'post': post
    }
    if request.user.id != post.author.id:
        messages.warning(request, "You're not authorized!")
        return redirect("main:post_list")
    if form.is_valid():
        form.save()
        messages.success(request, "Post updated successfully!")
        return redirect('main:post_details', slug=slug)

    return render(request, 'main_app/update_post.html', context)


@login_required()
def delete_post(request, slug):
    post = get_object_or_404(Post, slug=slug)
    context = {
        'post': post
    }
    if request.user.id != post.author.id:
        messages.warning(request, "You're not authorized!")
        return redirect("main:post_list")
    if request.method == 'POST':
        post.delete()
        messages.success(request, "Post deleted successfully!")
        return redirect('main:post_list')
    return render(request, 'main_app/delete_post.html', context)


@login_required()
def like_post(request, slug):
    if request.method == "POST":
        post = get_object_or_404(Post, slug=slug)
        like = Like.objects.filter(post=post, user=request.user)
        if like.exists():
            like.delete()
        else:
            Like.objects.create(user=request.user, post=post)
        return redirect('main:post_details', slug=slug)
    # The view main_app.views.like_post didn't return an HttpResponse object.
    # It returned None instead. ==> Request Method: GET
    return redirect('main:post_details', slug=slug)  # <== solution

src/main_app/templates/main_app/create_post.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}
  Create Post
{% endblock title %}

{% block content %}
    <h3>Create New Post</h3>
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit">POST</button>
    </form>
{% endblock content %}

src/main_app/templates/main_app/delete_post.html
{% extends "base.html" %}

{% block title %}
  Delete Post
{% endblock title %}

{% block content %}
    <form action="" method="POST">
        {% csrf_token %}
        <p>Are you sure that you want to delete "{{ post }}"</p>
        <input type="submit" value="Yes">
        <a href="{% url 'main:update_post' post.slug %}"><input type="button" value="No"></a>
    </form>
{% endblock content %}

src/main_app/templates/main_app/home_page.html
{% extends "base.html" %}

{% block title %}
  Welcome to Blog App
{% endblock title %}Home Page

{% block content %}
  <h1>Blog App</h1>
  <p>Welcome to home page!</p>
  <ul>
    <a href="{% url 'main:post_list' %}" style="text-decoration-line: none;">
      <li>Post List</li>
    </a>
    <a href="{% url 'main:create_post' %}" style="text-decoration-line: none;">
      <li>Create Post</li>
    </a>
  </ul>
{% endblock content %}

src/main_app/templates/main_app/post_details.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}
  Post Details
{% endblock title %}

{% block content %}
  <h3>{{post.title}}</h3>
  <img src="{{ post.image.url }}" alt="post_image" style="width: 400px;">
  <p>{{post.content}}</p>

  {% if user.id == post.author.id %}
    <a href="{% url 'main:update_post' post.slug %}"><input type="button" value="Change"></a>
  {% endif %}

  <form action="{% url 'main:like_post' post.slug %}" method="POST">
    {% csrf_token %}
    <input type="hidden" name="user">
    <input type="hidden" name="post">
    <button type="submit">Like</button>{{ post.get_like_count }}
  </form>
  
  <form action="" method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit">Comment</button>
  </form>

  {% for comment in post.get_comments %}
    <hr>
    <div>
      <p>{{ comment.content }}</p>
      <p>comment by {{ comment }}</p>
    </div>
  {% endfor %}

{% endblock content %}

src/main_app/templates/main_app/post_list.html
{% extends "base.html" %}

{% block title %}
  Post List
{% endblock title %}

{% block content %}

  <h3>Post List</h3>
  <div class="row mt-5">
    {% for post in post_list %}
      <div class="col-4">
          <div class="card shadow p-3 mb-5 bg-white rounded" style="width: 18rem; height: 25rem;">
              <img src="{{ post.image.url }}" class="card-img-top" alt="post_image">
              <hr>
              <div class="card-body">
                  <a href="{% url 'main:post_details' post.slug %}"><h5 class="card-title">{{post.title}}</h5></a>
                  <p class="card-text">{{post.content|truncatechars:20}}</p>
                  <p>
                      <span><i class="far fa-comment-alt ml-2"></i> {{ post.get_comment_count }}</span>
                      <span><i class="fas fa-eye ml-2"></i> {{ post.get_postview_count }}</span>
                      <span><i class="far fa-heart ml-2"></i> {{ post.get_like_count }}</span>
                  <p class="card-text"><small>
                          Posted {{ post.publish_date|timesince }} ago.
                      </small>
                  </p>
                  </p>
              </div>
          </div>
      </div>
      {% endfor %}
  </div>

{% endblock content %}

src/main_app/templates/main_app/update_post.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}
  Post Details
{% endblock title %}

{% block content %}
  <h3>Post Details</h3>
  <form action="" method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form|crispy }}
      <input type="submit" value="Update">
      <a href="{% url 'main:delete_post' post.slug %}"><input type="button" value="Delete"></a>
  </form>
{% endblock content %}